matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: vSCxOZdiTuwzgyO5znTlqLwcvL1cw9PQ1pJENKueBEpTeFCK7yR3f3OziRjLXwaPFW+4uMG+UkbXEwJI4VTdK3dVRCHst7+qtAcmTrzxhP61D6N2etP9lzcPyQN+hnG2GA93DCenxZQuy4vzEAfDQW1f08Y5Ik8EjValJN53KhkFOCDbi9IGM9uhGHm6L2jXMt2yK2kJUZnwPV5x8EduVTr1FuXnbyMfyDRpe3WdOMD+tVU585Y6O9pqPLf0KKDXFMpX1B3/qY3trQGkncq2OmyBO7GjeyOjJh5p+vHmvDc75f1j7Scak2luA8p3P9DsRvaZtsYUqbtp7D7bbbzDl3fFBRNsOgflMAJC3hpkyBAWBRAFkwr1Hxl87QI7FmQi3gTLqZiJktLlyhdUzn++fNzw5M61+vxHghBO+5bhHXcz4cpE1clsJpxHQKlMQ/+6L8aHg/3ADwmqYEY8rgl2VgQaTzZhiKS51VTtqEzvrxCuEcxyT3cZhSAYJ9mn3UFPMASNtbflJpCJJwYnOeidqVwoElfeKKSh+mdzisDl3mO9O3RC8dwD0DYRZpQUqfmJWPxuryrA1CZ+w9mjGtmII2OYXHBq3sfayyVl7aYsRStF60pomoZ/DbsNoyB2XPoIe/NeJv5dEY6kIARHfvkZZq8Tx367XHuP/PGPOqBuoEU=
