matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: zYJzs1BvnXdMxbTX3a3r3f6h8dWeTlCBVtFD1BFt/Nz9d5guMy4L1hxvBlvsgv96BsWWXREqvfZRG4ulMiUY8NYwSDB6mNfzxJumNImvdw5QLuwxLJ+iiJWHcShWnWacV3iyy5TJ62gbqoemujsqagLQ0VESqGdHelx8HUJHozqzB5AHUC8kt7vFc+uOJFKKXDhyhmc1bbivwG6+Pv8G760FREtXxJtr7uKIKsemlt8ctE4NaHnno/jDBic5RucgQEYJc5WjmD4hZPuArhSxO8C6JOgV2154ITcSpd1eCelyO3905YQaMLJOCJbJjI8X9FWQRI+tPj2D+OSMGBWc8z6MxSdlq/JTvgFuuxh3atBZW8ORaXhZ4ZPulj3VShRkZ7FMDBBilR5lkFmA0CJNIOvxdmSdWTl4PcdHvAf5OiPIZX2qWT4ZnLv7MQZYDa+kKrfdavKAla6YThvK4oPecSxig+buznpE6dV3fpLpp4Ajeqcd9iwMsTSjgRCVbqWzg5/7m291y3DZxtVNo/EVZTBkiu7taXjztaBIaUC8DPpF/V0tp3+U08AUkLhphezxB9VvO9YcPyNzLDjtTtkGeV3rkmin+shwOZcOIKsd7J+Nu87D496PQOe0SI9rG6GRDdGRt6Km445Ij/66GuuFUsK2Lr/q4lGO0rHs0OmN0Bc=
